apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-label-preserver
  namespace: default
  labels:
    app: node-label-preserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-label-preserver
  template:
    metadata:
      labels:
        app: node-label-preserver
    spec:
      serviceAccountName: node-label-preserver-sa
      containers:
        - name: node-label-preserver
          image: node-label-preserver:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RUST_LOG
              value: "info,kube=warn"
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
