name: Rust

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rust-cpu:
    name: CPU - Lint, build, and test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Install rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - uses: Swatinem/rust-cache@v2

      - name: Lint
        run: ./lint.sh

      - name: Build and Test
        run: |
          ./test.sh

      - name: Release Build
        run: cargo build --release
